# Generated by Django 5.2.1 on 2025-05-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('elevation', models.DecimalField(decimal_places=1, max_digits=3)),
                ('country_code', models.CharField(max_length=2)),
                ('timezone', models.CharField(max_length=100)),
                ('country_id', models.IntegerField()),
                ('country', models.CharField(max_length=255)),
                ('population', models.IntegerField()),
            ],
            options={
                'db_table': 'locations',
            },
        ),
    ]
