# Generated by Django 5.2.1 on 2025-05-16 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_location_country_alter_location_country_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.location')),
            ],
            options={
                'db_table': 'measurements',
                'unique_together': {('location', 'measurement', 'value')},
            },
        ),
    ]
