# Generated by Django 5.2.1 on 2025-05-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_historicalweather'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='elevation',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
    ]
