# Generated by Django 5.2.1 on 2025-05-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_location_elevation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalweather',
            name='value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='elevation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
