# Generated by Django 5.2.1 on 2025-05-17 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_historicalweather_value_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='historicalweather',
            unique_together={('location', 'measurement', 'value', 'time')},
        ),
    ]
